### ISSUE TITLE
qemu driver for kitchen is not working

### ISSUE THREAD

**Issue by aidda** [esmil/kitchen-qemu#10]
I tried to use this driver to use the qcow2 image for a kitchen but it doesn't work.
it sais:
```
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ClientError
>>>>>> Message: Could not load the 'qemu' driver from the load path. Please ensure that your driver is installed as a gem or included in your Gemfile if using Bundler.
```
Do you know what should I do!?
and this is kitchen diagnose -all:

```
error:
    exception: "#<Kitchen::ClientError: Could not load the 'qemu' driver from the
      load path. Please ensure that your driver is installed as a gem or included
      in your Gemfile if using Bundler.>"
    message: Could not load the 'qemu' driver from the load path. Please ensure that
      your driver is installed as a gem or included in your Gemfile if using Bundler.
    backtrace:
    - "/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/driver.rb:48:in
      `rescue in for_plugin'"
    - "/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/driver.rb:38:in
      `for_plugin'"
    - "/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/config.rb:233:in
      `new_driver'"
    - "/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/config.rb:246:in
      `new_instance'"
    - "/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/config.rb:142:in
      `block in build_instances'"
    - "/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/config.rb:141:in
      `map'"
    - "/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/config.rb:141:in
      `with_index'"
    - "/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/config.rb:141:in
      `build_instances'"
    - "/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/config.rb:117:in
      `instances'"
    - "/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:112:in
      `filtered_instances'"
    - "/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:142:in
      `parse_subcommand'"
    - "/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command/diagnose.rb:53:in
      `load_instances'"
    - "/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command/diagnose.rb:32:in
      `block in call'"
    - "/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command/diagnose.rb:73:in
      `record_failure'"
    - "/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command/diagnose.rb:32:in
      `call'"
    - "/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/cli.rb:53:in
      `perform'"
    - "/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/cli.rb:143:in
      `diagnose'"
    - "/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in
      `run'"
    - "/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in
      `invoke_command'"
    - "/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/cli.rb:334:in
      `invoke_task'"
    - "/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in
      `dispatch'"
    - "/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in
      `start'"
    - "/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/bin/kitchen:13:in
      `block in <top (required)>'"
    - "/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/errors.rb:171:in
      `with_friendly_errors'"
    - "/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/bin/kitchen:13:in
      `<top (required)>'"
    - "/usr/local/bin/kitchen:23:in `load'"
    - "/usr/local/bin/kitchen:23:in `<main>'"
```
I think it means it can not find a driver from kitchen driver list. Note that I have gem kitchen-qemu

**Comment by esmil** [comment]
It seems like you don't have the kitchen-qemu plugin installed. Maybe try
```sh
/opt/chefdk/embedded/bin/gem install kitchen-qemu
```

**Comment by aidda** [comment]
@esmil Thanks. The driver issue fixed!
So my next question is, I want to connect to my qcow2 image with specific username and key. 
now the kitchen.yml is like this 

```
---
driver:
  name: qemu

provisioner:
  name: chef_zero


platforms:
  - name: centos-7.3
    driver:
      image:
        - file: ///home/aida/Documents/qcow/rhel7_2017-04-10_1210_7536b7d.qcow2
        username: cloud-user
       ssh_key: $HOME/.ssh/id_rsa.pub
suites:
  - name: default
    run_list:
      - recipe[cookbooks::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
```

and this is an error log

```

cat .kitchen/logs/default-centos-73.log 
I, [2017-05-26T13:56:44.316231 #17604]  INFO -- default-centos-73: -----> Creating <default-centos-73>...
E, [2017-05-26T13:56:44.316523 #17604] ERROR -- default-centos-73: Create failed on instance <default-centos-73>.
E, [2017-05-26T13:56:44.316583 #17604] ERROR -- default-centos-73: ------Exception-------
E, [2017-05-26T13:56:44.316600 #17604] ERROR -- default-centos-73: Class: Kitchen::ActionFailed
E, [2017-05-26T13:56:44.316610 #17604] ERROR -- default-centos-73: Message: QEMU instance <default-centos-73> already running.
E, [2017-05-26T13:56:44.316619 #17604] ERROR -- default-centos-73: ----------------------
E, [2017-05-26T13:56:44.316631 #17604] ERROR -- default-centos-73: ------Backtrace-------
E, [2017-05-26T13:56:44.316640 #17604] ERROR -- default-centos-73: /var/lib/gems/2.3.0/gems/kitchen-qemu-0.2.8/lib/kitchen/driver/qemu.rb:169:in `create'
E, [2017-05-26T13:56:44.316648 #17604] ERROR -- default-centos-73: /var/lib/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:460:in `public_send'
E, [2017-05-26T13:56:44.316657 #17604] ERROR -- default-centos-73: /var/lib/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:460:in `block in perform_action'
E, [2017-05-26T13:56:44.316665 #17604] ERROR -- default-centos-73: /var/lib/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:527:in `synchronize_or_call'
E, [2017-05-26T13:56:44.316674 #17604] ERROR -- default-centos-73: /var/lib/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:489:in `block in action'
E, [2017-05-26T13:56:44.316682 #17604] ERROR -- default-centos-73: /usr/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
E, [2017-05-26T13:56:44.316690 #17604] ERROR -- default-centos-73: /var/lib/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:488:in `action'
E, [2017-05-26T13:56:44.316709 #17604] ERROR -- default-centos-73: /var/lib/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:460:in `perform_action'
E, [2017-05-26T13:56:44.316718 #17604] ERROR -- default-centos-73: /var/lib/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:370:in `create_action'
E, [2017-05-26T13:56:44.316730 #17604] ERROR -- default-centos-73: /var/lib/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:359:in `block in transition_to'
E, [2017-05-26T13:56:44.316739 #17604] ERROR -- default-centos-73: /var/lib/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:358:in `each'
E, [2017-05-26T13:56:44.316747 #17604] ERROR -- default-centos-73: /var/lib/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:358:in `transition_to'
E, [2017-05-26T13:56:44.316756 #17604] ERROR -- default-centos-73: /var/lib/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:124:in `create'
E, [2017-05-26T13:56:44.316764 #17604] ERROR -- default-centos-73: /var/lib/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:197:in `public_send'
E, [2017-05-26T13:56:44.316772 #17604] ERROR -- default-centos-73: /var/lib/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:197:in `run_action_in_thread'
E, [2017-05-26T13:56:44.316781 #17604] ERROR -- default-centos-73: /var/lib/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
E, [2017-05-26T13:56:44.316789 #17604] ERROR -- default-centos-73: ----End Backtrace-----
```

and as you see it`s not correct.
Can you help me to fix this issue?
Thanks

**Comment by aidda** [comment]
and also, how I can add the second disk to a machine in kitchen.yml?

**Comment by aidda** [comment]
I really appreciate your help if you can guide me to how can I add the second disk through a .kitchen.yml with qemu driver

**Comment by esmil** [comment]
If you see the main page https://github.com/esmil/kitchen-qemu under Configuration it has a pretty good description of all the options this plugin takes. The options goes into your `.kitchen.yml` under `driver` or under `driver` beneath `platforms` or `suites` depending on whether you want to define it globally, pr. platform or pr. suite respectively.

If you read there you'll notice the first option is `image` which seems to be what you're looking for. You might also notice that there is no option `ssh_key` so I don`t exactly know what you wont that to do.
