### ISSUE TITLE
Fail converging resource

### ISSUE THREAD

**Issue by marcmillien** [esmil/kitchen-qemu#6]
Hi, thanks for qemu implementation !
I'm currently trying it in replacement for vagrant :).
But I having an issue while converging resource, I think I'm missing something, but I'm not able to find where.
Sounds related the socket to connect to qemu is not found.

I'm using `kitchen 1.11.1` with `kitchen-qemu 02.7`
```
$ kitchen create
-----> Starting Kitchen (v1.11.1)
-----> Creating <default-lvm-jessie64>...
       KVM enabled.
       Spawning QEMU..
       Waiting for SSH..
       [SSH] Established
       Finished creating <default-lvm-jessie64> (0m7.33s).
-----> Kitchen is finished. (0m7.71s)
$ kitchen converge
-----> Starting Kitchen (v1.11.1)
-----> Converging <default-lvm-jessie64>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 4.3.5...
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #converge action: [cannot handle socket] on default-lvm-jessie64
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

Configuration:
```
driver:
  name: qemu

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.13

platforms:
  - name: lvm-jessie64
    driver:
      image: lvm-jessie64
      username: vagrant
      password: vagrant

suites:
  - name: default
    data_bags_path: "test/integration/default/data_bags"
    encrypted_data_bag_secret_key_path: "test/integration/default/encrypted_data_bag_secret"
    run_list:
    [...]
```

Logfile:
```
I, [2016-11-16T11:22:07.117980 #21969]  INFO -- Kitchen: -----> Starting Kitchen (v1.11.1)
I, [2016-11-16T11:22:07.488591 #21969]  INFO -- Kitchen: -----> Converging <default-lvm-jessie64>...
E, [2016-11-16T11:22:07.548014 #21969] ERROR -- Kitchen: ------Exception-------
E, [2016-11-16T11:22:07.548082 #21969] ERROR -- Kitchen: Class: Kitchen::ActionFailed
E, [2016-11-16T11:22:07.548105 #21969] ERROR -- Kitchen: Message: 1 actions failed.
>>>>>>     Failed to complete #converge action: [cannot handle socket] on default-lvm-jessie64
E, [2016-11-16T11:22:07.548122 #21969] ERROR -- Kitchen: ----------------------
E, [2016-11-16T11:22:07.548148 #21969] ERROR -- Kitchen: ------Backtrace-------
E, [2016-11-16T11:22:07.548163 #21969] ERROR -- Kitchen: /home/marcm/.rvm/gems/ruby-2.3.1-chef/gems/test-kitchen-1.11.1/lib/kitchen/command.rb:187:in `report_errors'
E, [2016-11-16T11:22:07.548176 #21969] ERROR -- Kitchen: /home/marcm/.rvm/gems/ruby-2.3.1-chef/gems/test-kitchen-1.11.1/lib/kitchen/command.rb:178:in `run_action'
E, [2016-11-16T11:22:07.548188 #21969] ERROR -- Kitchen: /home/marcm/.rvm/gems/ruby-2.3.1-chef/gems/test-kitchen-1.11.1/lib/kitchen/command/action.rb:39:in `block in call'
E, [2016-11-16T11:22:07.548200 #21969] ERROR -- Kitchen: /home/marcm/.rvm/rubies/ruby-2.3.1-chef/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
E, [2016-11-16T11:22:07.548212 #21969] ERROR -- Kitchen: /home/marcm/.rvm/gems/ruby-2.3.1-chef/gems/test-kitchen-1.11.1/lib/kitchen/command/action.rb:37:in `call'
E, [2016-11-16T11:22:07.548224 #21969] ERROR -- Kitchen: /home/marcm/.rvm/gems/ruby-2.3.1-chef/gems/test-kitchen-1.11.1/lib/kitchen/cli.rb:56:in `perform'
E, [2016-11-16T11:22:07.548235 #21969] ERROR -- Kitchen: /home/marcm/.rvm/gems/ruby-2.3.1-chef/gems/test-kitchen-1.11.1/lib/kitchen/cli.rb:185:in `block (2 levels) in <class:CLI>'
E, [2016-11-16T11:22:07.548247 #21969] ERROR -- Kitchen: /home/marcm/.rvm/gems/ruby-2.3.1-chef/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
E, [2016-11-16T11:22:07.548258 #21969] ERROR -- Kitchen: /home/marcm/.rvm/gems/ruby-2.3.1-chef/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
E, [2016-11-16T11:22:07.548269 #21969] ERROR -- Kitchen: /home/marcm/.rvm/gems/ruby-2.3.1-chef/gems/test-kitchen-1.11.1/lib/kitchen/cli.rb:326:in `invoke_task'
E, [2016-11-16T11:22:07.548280 #21969] ERROR -- Kitchen: /home/marcm/.rvm/gems/ruby-2.3.1-chef/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
E, [2016-11-16T11:22:07.548291 #21969] ERROR -- Kitchen: /home/marcm/.rvm/gems/ruby-2.3.1-chef/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
E, [2016-11-16T11:22:07.548302 #21969] ERROR -- Kitchen: /home/marcm/.rvm/gems/ruby-2.3.1-chef/gems/test-kitchen-1.11.1/bin/kitchen:13:in `block in <top (required)>'
E, [2016-11-16T11:22:07.548313 #21969] ERROR -- Kitchen: /home/marcm/.rvm/gems/ruby-2.3.1-chef/gems/test-kitchen-1.11.1/lib/kitchen/errors.rb:174:in `with_friendly_errors'
E, [2016-11-16T11:22:07.548324 #21969] ERROR -- Kitchen: /home/marcm/.rvm/gems/ruby-2.3.1-chef/gems/test-kitchen-1.11.1/bin/kitchen:13:in `<top (required)>'
E, [2016-11-16T11:22:07.548335 #21969] ERROR -- Kitchen: /home/marcm/.rvm/gems/ruby-2.3.1-chef/bin/kitchen:23:in `load'
E, [2016-11-16T11:22:07.548346 #21969] ERROR -- Kitchen: /home/marcm/.rvm/gems/ruby-2.3.1-chef/bin/kitchen:23:in `<main>'
E, [2016-11-16T11:22:07.548357 #21969] ERROR -- Kitchen: /home/marcm/.rvm/gems/ruby-2.3.1-chef/bin/ruby_executable_hooks:15:in `eval'
E, [2016-11-16T11:22:07.548367 #21969] ERROR -- Kitchen: /home/marcm/.rvm/gems/ruby-2.3.1-chef/bin/ruby_executable_hooks:15:in `<main>'
E, [2016-11-16T11:22:07.548378 #21969] ERROR -- Kitchen: ----End Backtrace-----
E, [2016-11-16T11:22:07.548388 #21969] ERROR -- Kitchen: -Composite Exception--
E, [2016-11-16T11:22:07.548398 #21969] ERROR -- Kitchen: Class: Kitchen::ActionFailed
E, [2016-11-16T11:22:07.548418 #21969] ERROR -- Kitchen: Message: Failed to complete #converge action: [cannot handle socket] on default-lvm-jessie64
E, [2016-11-16T11:22:07.548430 #21969] ERROR -- Kitchen: ----------------------
E, [2016-11-16T11:22:07.548441 #21969] ERROR -- Kitchen: ------Backtrace-------
E, [2016-11-16T11:22:07.548461 #21969] ERROR -- Kitchen: /home/marcm/.rvm/rubies/ruby-2.3.1-chef/lib/ruby/2.3.0/fileutils.rb:1379:in `copy'
E, [2016-11-16T11:22:07.548474 #21969] ERROR -- Kitchen: /home/marcm/.rvm/rubies/ruby-2.3.1-chef/lib/ruby/2.3.0/fileutils.rb:472:in `block in copy_entry'
E, [2016-11-16T11:22:07.548485 #21969] ERROR -- Kitchen: /home/marcm/.rvm/rubies/ruby-2.3.1-chef/lib/ruby/2.3.0/fileutils.rb:1498:in `wrap_traverse'
E, [2016-11-16T11:22:07.548495 #21969] ERROR -- Kitchen: /home/marcm/.rvm/rubies/ruby-2.3.1-chef/lib/ruby/2.3.0/fileutils.rb:1501:in `block in wrap_traverse'
E, [2016-11-16T11:22:07.548506 #21969] ERROR -- Kitchen: /home/marcm/.rvm/rubies/ruby-2.3.1-chef/lib/ruby/2.3.0/fileutils.rb:1500:in `each'
E, [2016-11-16T11:22:07.548517 #21969] ERROR -- Kitchen: /home/marcm/.rvm/rubies/ruby-2.3.1-chef/lib/ruby/2.3.0/fileutils.rb:1500:in `wrap_traverse'
E, [2016-11-16T11:22:07.548528 #21969] ERROR -- Kitchen: /home/marcm/.rvm/rubies/ruby-2.3.1-chef/lib/ruby/2.3.0/fileutils.rb:469:in `copy_entry'
E, [2016-11-16T11:22:07.548539 #21969] ERROR -- Kitchen: /home/marcm/.rvm/rubies/ruby-2.3.1-chef/lib/ruby/2.3.0/fileutils.rb:444:in `block in cp_r'
E, [2016-11-16T11:22:07.548549 #21969] ERROR -- Kitchen: /home/marcm/.rvm/rubies/ruby-2.3.1-chef/lib/ruby/2.3.0/fileutils.rb:1571:in `block in fu_each_src_dest'
E, [2016-11-16T11:22:07.548560 #21969] ERROR -- Kitchen: /home/marcm/.rvm/rubies/ruby-2.3.1-chef/lib/ruby/2.3.0/fileutils.rb:1580:in `block in fu_each_src_dest0'
E, [2016-11-16T11:22:07.548570 #21969] ERROR -- Kitchen: /home/marcm/.rvm/rubies/ruby-2.3.1-chef/lib/ruby/2.3.0/fileutils.rb:1578:in `each'
E, [2016-11-16T11:22:07.548581 #21969] ERROR -- Kitchen: /home/marcm/.rvm/rubies/ruby-2.3.1-chef/lib/ruby/2.3.0/fileutils.rb:1578:in `fu_each_src_dest0'
E, [2016-11-16T11:22:07.548592 #21969] ERROR -- Kitchen: /home/marcm/.rvm/rubies/ruby-2.3.1-chef/lib/ruby/2.3.0/fileutils.rb:1569:in `fu_each_src_dest'
E, [2016-11-16T11:22:07.548602 #21969] ERROR -- Kitchen: /home/marcm/.rvm/rubies/ruby-2.3.1-chef/lib/ruby/2.3.0/fileutils.rb:443:in `cp_r'
E, [2016-11-16T11:22:07.548613 #21969] ERROR -- Kitchen: /home/marcm/.rvm/gems/ruby-2.3.1-chef/gems/berkshelf-4.3.5/lib/berkshelf/berksfile.rb:653:in `block (2 levels) in vendor'
E, [2016-11-16T11:22:07.548623 #21969] ERROR -- Kitchen: /home/marcm/.rvm/gems/ruby-2.3.1-chef/gems/berkshelf-4.3.5/lib/berkshelf/berksfile.rb:635:in `each'
E, [2016-11-16T11:22:07.548634 #21969] ERROR -- Kitchen: /home/marcm/.rvm/gems/ruby-2.3.1-chef/gems/berkshelf-4.3.5/lib/berkshelf/berksfile.rb:635:in `block in vendor'
E, [2016-11-16T11:22:07.548660 #21969] ERROR -- Kitchen: /home/marcm/.rvm/rubies/ruby-2.3.1-chef/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
E, [2016-11-16T11:22:07.548671 #21969] ERROR -- Kitchen: /home/marcm/.rvm/gems/ruby-2.3.1-chef/gems/berkshelf-4.3.5/lib/berkshelf/berksfile.rb:628:in `vendor'
E, [2016-11-16T11:22:07.548681 #21969] ERROR -- Kitchen: /home/marcm/.rvm/gems/ruby-2.3.1-chef/gems/test-kitchen-1.11.1/lib/kitchen/provisioner/chef/berkshelf.rb:68:in `block in resolve'
E, [2016-11-16T11:22:07.548692 #21969] ERROR -- Kitchen: /home/marcm/.rvm/gems/ruby-2.3.1-chef/gems/thor-0.19.1/lib/thor/shell/basic.rb:20:in `mute'
E, [2016-11-16T11:22:07.548702 #21969] ERROR -- Kitchen: /home/marcm/.rvm/gems/ruby-2.3.1-chef/gems/test-kitchen-1.11.1/lib/kitchen/provisioner/chef/berkshelf.rb:64:in `resolve'
E, [2016-11-16T11:22:07.548713 #21969] ERROR -- Kitchen: /home/marcm/.rvm/gems/ruby-2.3.1-chef/gems/test-kitchen-1.11.1/lib/kitchen/provisioner/chef/common_sandbox.rb:329:in `block in resolve_with_berkshelf'
E, [2016-11-16T11:22:07.548725 #21969] ERROR -- Kitchen: /home/marcm/.rvm/gems/ruby-2.3.1-chef/gems/test-kitchen-1.11.1/lib/kitchen/provisioner/chef/common_sandbox.rb:328:in `synchronize'
E, [2016-11-16T11:22:07.548736 #21969] ERROR -- Kitchen: /home/marcm/.rvm/gems/ruby-2.3.1-chef/gems/test-kitchen-1.11.1/lib/kitchen/provisioner/chef/common_sandbox.rb:328:in `resolve_with_berkshelf'
E, [2016-11-16T11:22:07.548747 #21969] ERROR -- Kitchen: /home/marcm/.rvm/gems/ruby-2.3.1-chef/gems/test-kitchen-1.11.1/lib/kitchen/provisioner/chef/common_sandbox.rb:264:in `prepare_cookbooks'
E, [2016-11-16T11:22:07.548763 #21969] ERROR -- Kitchen: /home/marcm/.rvm/gems/ruby-2.3.1-chef/gems/test-kitchen-1.11.1/lib/kitchen/provisioner/chef/common_sandbox.rb:52:in `populate'
E, [2016-11-16T11:22:07.548794 #21969] ERROR -- Kitchen: /home/marcm/.rvm/gems/ruby-2.3.1-chef/gems/test-kitchen-1.11.1/lib/kitchen/provisioner/chef_base.rb:124:in `create_sandbox'
E, [2016-11-16T11:22:07.548806 #21969] ERROR -- Kitchen: /home/marcm/.rvm/gems/ruby-2.3.1-chef/gems/test-kitchen-1.11.1/lib/kitchen/provisioner/chef_zero.rb:53:in `create_sandbox'
E, [2016-11-16T11:22:07.548816 #21969] ERROR -- Kitchen: /home/marcm/.rvm/gems/ruby-2.3.1-chef/gems/test-kitchen-1.11.1/lib/kitchen/provisioner/base.rb:68:in `call'
E, [2016-11-16T11:22:07.548826 #21969] ERROR -- Kitchen: /home/marcm/.rvm/gems/ruby-2.3.1-chef/gems/test-kitchen-1.11.1/lib/kitchen/instance.rb:373:in `block in converge_action'
E, [2016-11-16T11:22:07.548837 #21969] ERROR -- Kitchen: /home/marcm/.rvm/gems/ruby-2.3.1-chef/gems/test-kitchen-1.11.1/lib/kitchen/instance.rb:513:in `synchronize_or_call'
E, [2016-11-16T11:22:07.548848 #21969] ERROR -- Kitchen: /home/marcm/.rvm/gems/ruby-2.3.1-chef/gems/test-kitchen-1.11.1/lib/kitchen/instance.rb:478:in `block in action'
E, [2016-11-16T11:22:07.548858 #21969] ERROR -- Kitchen: /home/marcm/.rvm/rubies/ruby-2.3.1-chef/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
E, [2016-11-16T11:22:07.548869 #21969] ERROR -- Kitchen: /home/marcm/.rvm/gems/ruby-2.3.1-chef/gems/test-kitchen-1.11.1/lib/kitchen/instance.rb:477:in `action'
E, [2016-11-16T11:22:07.548879 #21969] ERROR -- Kitchen: /home/marcm/.rvm/gems/ruby-2.3.1-chef/gems/test-kitchen-1.11.1/lib/kitchen/instance.rb:369:in `converge_action'
E, [2016-11-16T11:22:07.548889 #21969] ERROR -- Kitchen: /home/marcm/.rvm/gems/ruby-2.3.1-chef/gems/test-kitchen-1.11.1/lib/kitchen/instance.rb:348:in `block in transition_to'
E, [2016-11-16T11:22:07.548900 #21969] ERROR -- Kitchen: /home/marcm/.rvm/gems/ruby-2.3.1-chef/gems/test-kitchen-1.11.1/lib/kitchen/instance.rb:347:in `each'
E, [2016-11-16T11:22:07.548910 #21969] ERROR -- Kitchen: /home/marcm/.rvm/gems/ruby-2.3.1-chef/gems/test-kitchen-1.11.1/lib/kitchen/instance.rb:347:in `transition_to'
E, [2016-11-16T11:22:07.548921 #21969] ERROR -- Kitchen: /home/marcm/.rvm/gems/ruby-2.3.1-chef/gems/test-kitchen-1.11.1/lib/kitchen/instance.rb:138:in `converge'
E, [2016-11-16T11:22:07.548931 #21969] ERROR -- Kitchen: /home/marcm/.rvm/gems/ruby-2.3.1-chef/gems/test-kitchen-1.11.1/lib/kitchen/command.rb:201:in `public_send'
E, [2016-11-16T11:22:07.548942 #21969] ERROR -- Kitchen: /home/marcm/.rvm/gems/ruby-2.3.1-chef/gems/test-kitchen-1.11.1/lib/kitchen/command.rb:201:in `run_action_in_thread'
E, [2016-11-16T11:22:07.548953 #21969] ERROR -- Kitchen: /home/marcm/.rvm/gems/ruby-2.3.1-chef/gems/test-kitchen-1.11.1/lib/kitchen/command.rb:173:in `block (2 levels) in run_action'
E, [2016-11-16T11:22:07.548963 #21969] ERROR -- Kitchen: ----End Backtrace-----
E, [2016-11-16T11:22:07.548973 #21969] ERROR -- Kitchen: ---Nested Exception---
E, [2016-11-16T11:22:07.548983 #21969] ERROR -- Kitchen: Class: Kitchen::ActionFailed
E, [2016-11-16T11:22:07.548993 #21969] ERROR -- Kitchen: Message: Failed to complete #converge action: [cannot handle socket]
E, [2016-11-16T11:22:07.549004 #21969] ERROR -- Kitchen: ----------------------
E, [2016-11-16T11:22:07.549014 #21969] ERROR -- Kitchen: ------Backtrace-------
E, [2016-11-16T11:22:07.549024 #21969] ERROR -- Kitchen: /home/marcm/.rvm/rubies/ruby-2.3.1-chef/lib/ruby/2.3.0/fileutils.rb:1379:in `copy'
E, [2016-11-16T11:22:07.549035 #21969] ERROR -- Kitchen: /home/marcm/.rvm/rubies/ruby-2.3.1-chef/lib/ruby/2.3.0/fileutils.rb:472:in `block in copy_entry'
E, [2016-11-16T11:22:07.549045 #21969] ERROR -- Kitchen: /home/marcm/.rvm/rubies/ruby-2.3.1-chef/lib/ruby/2.3.0/fileutils.rb:1498:in `wrap_traverse'
E, [2016-11-16T11:22:07.549056 #21969] ERROR -- Kitchen: /home/marcm/.rvm/rubies/ruby-2.3.1-chef/lib/ruby/2.3.0/fileutils.rb:1501:in `block in wrap_traverse'
E, [2016-11-16T11:22:07.549070 #21969] ERROR -- Kitchen: /home/marcm/.rvm/rubies/ruby-2.3.1-chef/lib/ruby/2.3.0/fileutils.rb:1500:in `each'
E, [2016-11-16T11:22:07.549081 #21969] ERROR -- Kitchen: /home/marcm/.rvm/rubies/ruby-2.3.1-chef/lib/ruby/2.3.0/fileutils.rb:1500:in `wrap_traverse'
E, [2016-11-16T11:22:07.549114 #21969] ERROR -- Kitchen: /home/marcm/.rvm/rubies/ruby-2.3.1-chef/lib/ruby/2.3.0/fileutils.rb:469:in `copy_entry'
E, [2016-11-16T11:22:07.549139 #21969] ERROR -- Kitchen: /home/marcm/.rvm/rubies/ruby-2.3.1-chef/lib/ruby/2.3.0/fileutils.rb:444:in `block in cp_r'
E, [2016-11-16T11:22:07.549150 #21969] ERROR -- Kitchen: /home/marcm/.rvm/rubies/ruby-2.3.1-chef/lib/ruby/2.3.0/fileutils.rb:1571:in `block in fu_each_src_dest'
E, [2016-11-16T11:22:07.549160 #21969] ERROR -- Kitchen: /home/marcm/.rvm/rubies/ruby-2.3.1-chef/lib/ruby/2.3.0/fileutils.rb:1580:in `block in fu_each_src_dest0'
E, [2016-11-16T11:22:07.549171 #21969] ERROR -- Kitchen: /home/marcm/.rvm/rubies/ruby-2.3.1-chef/lib/ruby/2.3.0/fileutils.rb:1578:in `each'
E, [2016-11-16T11:22:07.549182 #21969] ERROR -- Kitchen: /home/marcm/.rvm/rubies/ruby-2.3.1-chef/lib/ruby/2.3.0/fileutils.rb:1578:in `fu_each_src_dest0'
E, [2016-11-16T11:22:07.549193 #21969] ERROR -- Kitchen: /home/marcm/.rvm/rubies/ruby-2.3.1-chef/lib/ruby/2.3.0/fileutils.rb:1569:in `fu_each_src_dest'
E, [2016-11-16T11:22:07.549204 #21969] ERROR -- Kitchen: /home/marcm/.rvm/rubies/ruby-2.3.1-chef/lib/ruby/2.3.0/fileutils.rb:443:in `cp_r'
E, [2016-11-16T11:22:07.549214 #21969] ERROR -- Kitchen: /home/marcm/.rvm/gems/ruby-2.3.1-chef/gems/berkshelf-4.3.5/lib/berkshelf/berksfile.rb:653:in `block (2 levels) in vendor'
E, [2016-11-16T11:22:07.549225 #21969] ERROR -- Kitchen: /home/marcm/.rvm/gems/ruby-2.3.1-chef/gems/berkshelf-4.3.5/lib/berkshelf/berksfile.rb:635:in `each'
E, [2016-11-16T11:22:07.549236 #21969] ERROR -- Kitchen: /home/marcm/.rvm/gems/ruby-2.3.1-chef/gems/berkshelf-4.3.5/lib/berkshelf/berksfile.rb:635:in `block in vendor'
E, [2016-11-16T11:22:07.549246 #21969] ERROR -- Kitchen: /home/marcm/.rvm/rubies/ruby-2.3.1-chef/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
E, [2016-11-16T11:22:07.549257 #21969] ERROR -- Kitchen: /home/marcm/.rvm/gems/ruby-2.3.1-chef/gems/berkshelf-4.3.5/lib/berkshelf/berksfile.rb:628:in `vendor'
E, [2016-11-16T11:22:07.549267 #21969] ERROR -- Kitchen: /home/marcm/.rvm/gems/ruby-2.3.1-chef/gems/test-kitchen-1.11.1/lib/kitchen/provisioner/chef/berkshelf.rb:68:in `block in resolve'
E, [2016-11-16T11:22:07.549278 #21969] ERROR -- Kitchen: /home/marcm/.rvm/gems/ruby-2.3.1-chef/gems/thor-0.19.1/lib/thor/shell/basic.rb:20:in `mute'
E, [2016-11-16T11:22:07.549288 #21969] ERROR -- Kitchen: /home/marcm/.rvm/gems/ruby-2.3.1-chef/gems/test-kitchen-1.11.1/lib/kitchen/provisioner/chef/berkshelf.rb:64:in `resolve'
E, [2016-11-16T11:22:07.549299 #21969] ERROR -- Kitchen: /home/marcm/.rvm/gems/ruby-2.3.1-chef/gems/test-kitchen-1.11.1/lib/kitchen/provisioner/chef/common_sandbox.rb:329:in `block in resolve_with_berkshelf'
E, [2016-11-16T11:22:07.549310 #21969] ERROR -- Kitchen: /home/marcm/.rvm/gems/ruby-2.3.1-chef/gems/test-kitchen-1.11.1/lib/kitchen/provisioner/chef/common_sandbox.rb:328:in `synchronize'
E, [2016-11-16T11:22:07.549320 #21969] ERROR -- Kitchen: /home/marcm/.rvm/gems/ruby-2.3.1-chef/gems/test-kitchen-1.11.1/lib/kitchen/provisioner/chef/common_sandbox.rb:328:in `resolve_with_berkshelf'
E, [2016-11-16T11:22:07.549331 #21969] ERROR -- Kitchen: /home/marcm/.rvm/gems/ruby-2.3.1-chef/gems/test-kitchen-1.11.1/lib/kitchen/provisioner/chef/common_sandbox.rb:264:in `prepare_cookbooks'
E, [2016-11-16T11:22:07.549341 #21969] ERROR -- Kitchen: /home/marcm/.rvm/gems/ruby-2.3.1-chef/gems/test-kitchen-1.11.1/lib/kitchen/provisioner/chef/common_sandbox.rb:52:in `populate'
E, [2016-11-16T11:22:07.549361 #21969] ERROR -- Kitchen: /home/marcm/.rvm/gems/ruby-2.3.1-chef/gems/test-kitchen-1.11.1/lib/kitchen/provisioner/chef_base.rb:124:in `create_sandbox'
E, [2016-11-16T11:22:07.549372 #21969] ERROR -- Kitchen: /home/marcm/.rvm/gems/ruby-2.3.1-chef/gems/test-kitchen-1.11.1/lib/kitchen/provisioner/chef_zero.rb:53:in `create_sandbox'
E, [2016-11-16T11:22:07.549387 #21969] ERROR -- Kitchen: /home/marcm/.rvm/gems/ruby-2.3.1-chef/gems/test-kitchen-1.11.1/lib/kitchen/provisioner/base.rb:68:in `call'
E, [2016-11-16T11:22:07.549399 #21969] ERROR -- Kitchen: /home/marcm/.rvm/gems/ruby-2.3.1-chef/gems/test-kitchen-1.11.1/lib/kitchen/instance.rb:373:in `block in converge_action'
E, [2016-11-16T11:22:07.549409 #21969] ERROR -- Kitchen: /home/marcm/.rvm/gems/ruby-2.3.1-chef/gems/test-kitchen-1.11.1/lib/kitchen/instance.rb:513:in `synchronize_or_call'
E, [2016-11-16T11:22:07.549420 #21969] ERROR -- Kitchen: /home/marcm/.rvm/gems/ruby-2.3.1-chef/gems/test-kitchen-1.11.1/lib/kitchen/instance.rb:478:in `block in action'
E, [2016-11-16T11:22:07.549431 #21969] ERROR -- Kitchen: /home/marcm/.rvm/rubies/ruby-2.3.1-chef/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
E, [2016-11-16T11:22:07.549441 #21969] ERROR -- Kitchen: /home/marcm/.rvm/gems/ruby-2.3.1-chef/gems/test-kitchen-1.11.1/lib/kitchen/instance.rb:477:in `action'
E, [2016-11-16T11:22:07.549452 #21969] ERROR -- Kitchen: /home/marcm/.rvm/gems/ruby-2.3.1-chef/gems/test-kitchen-1.11.1/lib/kitchen/instance.rb:369:in `converge_action'
E, [2016-11-16T11:22:07.549462 #21969] ERROR -- Kitchen: /home/marcm/.rvm/gems/ruby-2.3.1-chef/gems/test-kitchen-1.11.1/lib/kitchen/instance.rb:348:in `block in transition_to'
E, [2016-11-16T11:22:07.549473 #21969] ERROR -- Kitchen: /home/marcm/.rvm/gems/ruby-2.3.1-chef/gems/test-kitchen-1.11.1/lib/kitchen/instance.rb:347:in `each'
E, [2016-11-16T11:22:07.549483 #21969] ERROR -- Kitchen: /home/marcm/.rvm/gems/ruby-2.3.1-chef/gems/test-kitchen-1.11.1/lib/kitchen/instance.rb:347:in `transition_to'
E, [2016-11-16T11:22:07.549494 #21969] ERROR -- Kitchen: /home/marcm/.rvm/gems/ruby-2.3.1-chef/gems/test-kitchen-1.11.1/lib/kitchen/instance.rb:138:in `converge'
E, [2016-11-16T11:22:07.549504 #21969] ERROR -- Kitchen: /home/marcm/.rvm/gems/ruby-2.3.1-chef/gems/test-kitchen-1.11.1/lib/kitchen/command.rb:201:in `public_send'
E, [2016-11-16T11:22:07.549515 #21969] ERROR -- Kitchen: /home/marcm/.rvm/gems/ruby-2.3.1-chef/gems/test-kitchen-1.11.1/lib/kitchen/command.rb:201:in `run_action_in_thread'
E, [2016-11-16T11:22:07.549525 #21969] ERROR -- Kitchen: /home/marcm/.rvm/gems/ruby-2.3.1-chef/gems/test-kitchen-1.11.1/lib/kitchen/command.rb:173:in `block (2 levels) in run_action'
E, [2016-11-16T11:22:07.549536 #21969] ERROR -- Kitchen: ----End Backtrace-----
```

Thanks in advance.

**Comment by esmil** [comment]
Hi Marc,

Thanks for the bug report. I've actually got an email about this issue before.
I'm glad to see that kitchen create works for you because that's where the kitchen-qemu code is run. However when kitchen converge is run the kitchen framework takes over and should be content with using the ssh connection that was established during the create phase.
So since no kitchen-qemu code is involved when you try to converge I'm guessing something in your image is not as berkshelf expects it to be, but I'm not too sure. We use librarian-chef instead of berkshelf for all our cookbooks at work and I've never seen any problem with that.

I'll see if I can reproduce it locally..

**Comment by esmil** [comment]
Ah! I think I cracked it :)

So in order to test your cookbook inside the guest Berkshelf copies the current directory and everything below it (except the stuff specified in the chefignore file) to the guest via a temporary directory in /tmp.
However it fails if there are any named unix sockets and kitchen-qemu makes Qemu create several named unix sockets in the .kitchen folder that kitchen-qemu uses to communicate with the running instances.

So the solution seems to be to make Berkshelf ignore the .kitchen directory by adding it the chefignore file. Eg.:

```
echo .kitchen >> chefignore
```

**Comment by marcmillien** [comment]
Haha, that's it !
Thanks a lot :).
I have network issue now, but it's a question of qemu configuration ^^.
